stages:
  prepare:
    cmd: python prepare.py
    deps:
    - data/
    outs:
    - prepared/
  train:
    cmd: python train.py
    deps:
    - prepared/
    outs:
    - ./summary.json
metrics:
- ./summary.json
